package com.zhidian.app.sdk.db.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "login_user".
 */
public class LoginUser implements java.io.Serializable {

    private Long id;
    /** Not-null value. */
    private String toker;
    private long userId;
    /** Not-null value. */
    private String userName;
    /** Not-null value. */
    private String password;
    private String relaveName;
    private int status;
    private Long lastLoginTime;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public LoginUser() {
    }

    public LoginUser(Long id) {
        this.id = id;
    }

    public LoginUser(Long id, String toker, long userId, String userName, String password, String relaveName, int status, Long lastLoginTime) {
        this.id = id;
        this.toker = toker;
        this.userId = userId;
        this.userName = userName;
        this.password = password;
        this.relaveName = relaveName;
        this.status = status;
        this.lastLoginTime = lastLoginTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getToker() {
        return toker;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setToker(String toker) {
        this.toker = toker;
    }

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    /** Not-null value. */
    public String getUserName() {
        return userName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /** Not-null value. */
    public String getPassword() {
        return password;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPassword(String password) {
        this.password = password;
    }

    public String getRelaveName() {
        return relaveName;
    }

    public void setRelaveName(String relaveName) {
        this.relaveName = relaveName;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public Long getLastLoginTime() {
        return lastLoginTime;
    }

    public void setLastLoginTime(Long lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
